use GradoviSrbije;
go
insert into Mesto (Naziv) values 
('Ada'),
('Aeksandrovac'),
('Aleksinac'),
('Aleksinački Rudnik'),
('Alibunar'),
('Apatin'),
('Arandelovac'),
('Arilje'),
('Babušnica'),
('Batočina'),
('Bajina Bašta') ,
('Bajmok' ),
('Baljevac'),
('Banatski Karlovac') ,
('Banja Koviljaca'),
('Bač'),
('Bačka Palanka') ,
('Bačka Topola') ,
('Bački Jarak'),
('Bački Petrovac') ,
('Begeč'),
('Belanovica') ,
('Bela Palanka'),
('Bela Crkva'),
('Beli Potok') ,
('Belo Polje') ,
('Batajnica') ,
('Beograd') ,
('Beocin' ),
('Becej' ),
('Blace'),
('Bogatic') ,
('Boljevac'),
('Bor' ),
('Borca' ),
('Bosilegrad' ),
('Brza Palanka') ,
('Brus'),
('Bujanovac'),
('Valjevo'),
('Velika Plana 8'),
('Veliki Crljeni' ),
('Veliko Gradište'),
('Vladicin Han') ,
('Vlasotince') ,
('Vranje' ),
('Vranjska Banja 2'),
('Vrbas') ,
('Vrnjacka Banja') ,
('Vršac'),
('Vučje'),
('Gornji Milanovac'),
('Grdelica'),
('Grocka'),
('Guča'),
('Despotovac'),
('Divčibare'),
('Dimitrovgrad'),
('Dobanovci'),
('Donji Milanovac'),
('Žabalj'),
('Žitište'),
('Zaječar'),
('Zlatibor'),
('Zrenjanin'),
('Ivanjica'),
('Inđija'),
('Irig'),
('Jagodina'),
('Jaša Tomić') ,
('Jošanička Banja'),
('Kanjiža'),
('Kačarevo'),
('Kikinda'),
('Kladovo'),
('Knjaževac'),
('Kovačica'),
('Kovin' ),
('Kosjerić'),
('Kostolac' ),
('Kragujevac'), 
('Kraljevo') ,
('Krupanj'),
('Kruševac'),
('Kula'),
('Kuršumlija'),
('Kuršumlijska Banja') ,
('Kučevo'),
('Lazarevac'),
('Lajkovac'),
('Lapovo'),
('Lebane'),
('Leskovac') ,
('Loznica'),
('Lučani'),
('Ljig'),
('Majdanpek'),
('Mali Zvornik'),
('Mataruška Banja'),
('Mačvanska Mitrovica') ,
('Medveđa'),
('Mionica'),
('Mladenovac') ,
('Mol'),
('Negotin') ,
('Niš'),
('Niška Banja'),
('Nova Varoš'),
('Novi Bečej'),
('Novi Kneževac') ,
('Novi Pazar'),
('Novi Sad'),
('Obrenovac'),
('Ovča'),
('Opovo'),
('Ostružnica'),
('Palić'),
('Pančevo'),
('Petrovaradin'),
('Petrovac') ,
('Peć'),
('Pećani' ),
('Pinosava') ,
('Pirot' ),
('Podujevo' ),
('Požarevac') ,
('Požega'),
('Priboj'),
('Prijepolje') ,
('Priština'),
('Prizren'),
('Prokuplje') ,
('Ralja' ),
('Rača' ),
('Raška' ),
('Resavica'),
('Ribnica') ,
('Rudovci') ,
('Ruma' ),
('Rucka') ,
('Svilajnac'),
('Svrljig' ),
('Sevojno') ,
('Senta' ),
('Sijarinska Banja'),
('Sjenica') ,
('Smederevo' ),
('Smederevska Palanka' ),
('Sokobanja' ),
('Sombor' ),
('Sopot'),
('Srbobran') ,
('Sremska Kamenica') ,
('Sremska Mitrovica'),
('Sremski Karlovci') ,
('Stara Pazova' ),
('Starčevo') ,
('Subotica' ),
('Surdulica') ,
('Surčin' ),
('Temerin'),
('Titel') ,
('Topola') ,
('Trstenik'),
('Tutin'),
('Ćićevac'),
('Ćuprija'),
('Ub'),
('Užice'),
('Umka'),
('Uljma'),
('Futog'),
('Crvenka'),
('Čajetina'),
('Čačak'),
('Čoka'),
('Čelarevo'),
('Šabac'),
('Šid')

select * from Mesto